/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chatclient;

import java.io.*;
import java.net.*;
import javax.swing.*;

/**
 *
 * @author twofa
 */
public class SecureChatMessenger extends javax.swing.JFrame {

    private Socket socket;
    private PrintWriter writer;
    private BufferedReader reader;
    private String username;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SecureChatMessenger.class.getName());

    /**
     * Creates new form SecureChatMessenger
     */
    public SecureChatMessenger() {
        // Networking variables
        initComponents();
    }

    // This method connects to the server and starts listening
    public void startClient() {
        try {
            // Ask for name
            socket = new Socket("localhost", 1234);
            writer = new PrintWriter(socket.getOutputStream(), true);
            reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));

            String serverResponse = reader.readLine();
            if (serverResponse != null) {
                String status = EncryptionUtil.decrypt(serverResponse);

                if ("AUTH_REQUEST".equals(status)) {
                    // Ask the user for the password
                    String pass = JOptionPane.showInputDialog(this, "Enter Group Chat Password:");
                    // Encrypt and send it back to server6
                    writer.println(EncryptionUtil.encrypt(pass));

                    // Wait for server to say if it's okay
                    String authResult = EncryptionUtil.decrypt(reader.readLine());
                    if (!"AUTH_SUCCESS".equals(authResult)) {
                        JOptionPane.showMessageDialog(this, "Wrong Password! Closing...");
                        System.exit(0);
                        return;
                    }
                }
            }
            username = JOptionPane.showInputDialog(this, "Enter your username:");
            if (username == null || username.trim().isEmpty()) {
                username = "User" + (int) (Math.random() * 1000);
            }

            writer.println(EncryptionUtil.encrypt(username + " joined the chat."));
            // Connect to server (Ensure Server is running first!)

            // Background thread to listen for messages
            new Thread(() -> {
                try {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        System.out.println("[Network Packet Received]: " + line);
                        String decrypted = EncryptionUtil.decrypt(line);
                        chatArea.append(decrypted + "\n");
                        chatArea.setCaretPosition(chatArea.getDocument().getLength());
                    }
                } catch (IOException e) {
                    chatArea.append("Connection to server lost.\n");
                }
            }).start();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Could not connect to server. Is it running?");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        messageField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SecureChat Messenger - [Logged In]");
        setBackground(new java.awt.Color(153, 153, 153));
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Encrypted Chat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        chatArea.setEditable(false);
        chatArea.setColumns(20);
        chatArea.setRows(5);
        jScrollPane1.setViewportView(chatArea);

        messageField.setForeground(new java.awt.Color(204, 204, 204));
        messageField.setText("Type message here...");
        messageField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                messageFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                messageFieldFocusLost(evt);
            }
        });
        messageField.addActionListener(this::messageFieldActionPerformed);

        sendButton.setText("Send");
        sendButton.addActionListener(this::sendButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendButton))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messageField)
                    .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String text = messageField.getText().trim();

        if (!text.isEmpty() && !text.equals("Type message here...")) {

            String fullMessage = username + ": " + text;

            // 1. Encrypt the message
            String encrypted = EncryptionUtil.encrypt(fullMessage);

            // 2. Send the encrypted message to the server (ONLY ONCE)
            writer.println(encrypted);

            // 3. LOG to console for the professor to see
            System.out.println("[Network Packet Sent]: " + encrypted);

            // 4. Clear the field and put the hint back
            messageField.setText("");
            messageFieldFocusLost(null);
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void messageFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageFieldFocusGained
        if (messageField.getText().equals("Type message here...")) {
            messageField.setText(""); // Clear the box
            messageField.setForeground(java.awt.Color.BLACK); // Change text color to black for typing
        }
// TODO add your handling code here:
    }//GEN-LAST:event_messageFieldFocusGained

    private void messageFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messageFieldFocusLost
        if (messageField.getText().isEmpty()) {
            messageField.setForeground(java.awt.Color.GRAY); // Make it gray again
            messageField.setText("Type message here..."); // Put the hint back
        }
// TODO add your handling code here:
    }//GEN-LAST:event_messageFieldFocusLost

    private void messageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageFieldActionPerformed

        sendButtonActionPerformed(evt);
    }//GEN-LAST:event_messageFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            SecureChatMessenger scm = new SecureChatMessenger();
            scm.setVisible(true);
            scm.startClient(); // Start connection after window appears
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageField;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
